// <auto-generated />
using System;
using InvoicesSystem.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoicesSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103175553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "contact_type", new[] { "email", "phone", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invoice_status", new[] { "draft", "final", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "person_type", new[] { "natural", "juridica" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_address");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_address");

                    b.Property<int>("IdCity")
                        .HasColumnType("integer")
                        .HasColumnName("id_city");

                    b.HasKey("IdAddress");

                    b.HasIndex("IdCity");

                    b.ToTable("address");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_city");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCity"));

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer")
                        .HasColumnName("id_department");

                    b.Property<string>("NameCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_city");

                    b.HasKey("IdCity");

                    b.HasIndex("IdDepartment");

                    b.ToTable("city");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_country");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCountry"));

                    b.Property<string>("Cod_country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cod_country");

                    b.Property<string>("Name_country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_country");

                    b.HasKey("IdCountry");

                    b.ToTable("country");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Customer", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCustomer"));

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("CommercialName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commercial_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer")
                        .HasColumnName("id_address");

                    b.Property<int>("IdTaxRegime")
                        .HasColumnType("integer")
                        .HasColumnName("id_tax_regime");

                    b.Property<int>("IdTaxResponsibility")
                        .HasColumnType("integer")
                        .HasColumnName("id_tax_responsibility");

                    b.Property<int>("IdTypeIdentification")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_identification");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("PersonType")
                        .HasColumnType("integer")
                        .HasColumnName("person_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdCustomer");

                    b.HasIndex("IdAddress");

                    b.HasIndex("IdTaxRegime");

                    b.HasIndex("IdTaxResponsibility");

                    b.HasIndex("IdTypeIdentification");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.CustomerContact", b =>
                {
                    b.Property<int>("IdCustomerContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_customer_contact");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCustomerContact"));

                    b.Property<int>("ContactType")
                        .HasColumnType("integer")
                        .HasColumnName("contact_type");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdCustomerContact");

                    b.HasIndex("IdCustomer");

                    b.ToTable("customer_contact");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_department");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartment"));

                    b.Property<int>("IdCountry")
                        .HasColumnType("integer")
                        .HasColumnName("id_country");

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_department");

                    b.HasKey("IdDepartment");

                    b.HasIndex("IdCountry");

                    b.ToTable("department");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("IdInvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_invoice");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInvoice"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomerIdCustomer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    b.Property<int?>("IdIssuer")
                        .HasColumnType("integer")
                        .HasColumnName("id_issuer");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<int?>("IssuerIdIssuer")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_tax");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdInvoice");

                    b.HasIndex("CustomerIdCustomer");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdIssuer");

                    b.HasIndex("IssuerIdIssuer");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("integer")
                        .HasColumnName("id_invoice")
                        .HasColumnOrder(0);

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("id_product")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdInvoice", "IdProduct");

                    b.HasIndex("IdProduct");

                    b.ToTable("invoice_detail");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoiceDetailTax", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("integer")
                        .HasColumnName("id_invoice")
                        .HasColumnOrder(0);

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("id_product")
                        .HasColumnOrder(1);

                    b.Property<int>("IdTax")
                        .HasColumnType("integer")
                        .HasColumnName("id_tax")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_base");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdInvoice", "IdProduct", "IdTax");

                    b.HasIndex("IdTax");

                    b.ToTable("invoice_detail_tax");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoicePayment", b =>
                {
                    b.Property<int>("IdInvoice")
                        .HasColumnType("integer")
                        .HasColumnName("id_invoice")
                        .HasColumnOrder(0);

                    b.Property<int>("IdPaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("id_payment_method")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdInvoice", "IdPaymentMethod");

                    b.HasIndex("IdPaymentMethod");

                    b.ToTable("invoice_payment");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Issuer", b =>
                {
                    b.Property<int>("IdIssuer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_issuer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIssuer"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("CommercialName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commercial_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer")
                        .HasColumnName("id_address");

                    b.Property<int>("IdTaxRegime")
                        .HasColumnType("integer")
                        .HasColumnName("id_tax_regime");

                    b.Property<int>("IdTaxResponsibility")
                        .HasColumnType("integer")
                        .HasColumnName("id_tax_responsibility");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identification_number");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("website");

                    b.HasKey("IdIssuer");

                    b.HasIndex("IdAddress");

                    b.HasIndex("IdTaxRegime");

                    b.HasIndex("IdTaxResponsibility");

                    b.ToTable("issuer");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("IdPaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_payment_method");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaymentMethod"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("method_name");

                    b.HasKey("IdPaymentMethod");

                    b.ToTable("payment_method");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("CodeProduct")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code_product");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_name");

                    b.Property<string>("UnitMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_measure");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("IdProduct");

                    b.ToTable("product");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.ProductTax", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("id_product")
                        .HasColumnOrder(0);

                    b.Property<int>("IdTax")
                        .HasColumnType("integer")
                        .HasColumnName("id_tax")
                        .HasColumnOrder(1);

                    b.HasKey("IdProduct", "IdTax");

                    b.HasIndex("IdTax");

                    b.ToTable("product_tax");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Tax", b =>
                {
                    b.Property<int>("IdTax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tax");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTax"));

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_name");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tax_rate");

                    b.HasKey("IdTax");

                    b.ToTable("tax");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.TaxRegime", b =>
                {
                    b.Property<int>("IdTaxRegime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tax_regime");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTaxRegime"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.HasKey("IdTaxRegime");

                    b.ToTable("tax_regime");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.TaxResponsibility", b =>
                {
                    b.Property<int>("IdTaxResponsibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tax_responsibility");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTaxResponsibility"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.HasKey("IdTaxResponsibility");

                    b.ToTable("tax_responsibility");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.TypeIdentification", b =>
                {
                    b.Property<int>("IdTypeIdentification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type_identification");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeIdentification"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("IdTypeIdentification");

                    b.ToTable("type_identification");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdUser");

                    b.ToTable("users");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Address", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.City", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Department", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Customer", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.TaxRegime", "TaxRegime")
                        .WithMany("Customers")
                        .HasForeignKey("IdTaxRegime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.TaxResponsibility", "TaxResponsibility")
                        .WithMany("Customers")
                        .HasForeignKey("IdTaxResponsibility")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.TypeIdentification", "TypeIdentification")
                        .WithMany("Customers")
                        .HasForeignKey("IdTypeIdentification")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("TaxRegime");

                    b.Navigation("TaxResponsibility");

                    b.Navigation("TypeIdentification");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.CustomerContact", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Customer", "Customer")
                        .WithMany("CustomerContacts")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Department", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Country", "Country")
                        .WithMany("Departments")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Invoice", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Customer", null)
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerIdCustomer");

                    b.HasOne("InvoicesSystem.API.Models.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_invoice_customer");

                    b.HasOne("InvoicesSystem.API.Models.Entities.Issuer", "Issuer")
                        .WithMany()
                        .HasForeignKey("IdIssuer")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_invoice_issuer");

                    b.HasOne("InvoicesSystem.API.Models.Entities.Issuer", null)
                        .WithMany("Invoices")
                        .HasForeignKey("IssuerIdIssuer");

                    b.Navigation("Customer");

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("IdInvoice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoiceDetailTax", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Tax", "Tax")
                        .WithMany("InvoiceDetailTaxes")
                        .HasForeignKey("IdTax")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.InvoiceDetail", "InvoiceDetail")
                        .WithMany("InvoiceDetailTaxes")
                        .HasForeignKey("IdInvoice", "IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceDetail");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoicePayment", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Invoice", "Invoice")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("IdInvoice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("IdPaymentMethod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Issuer", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Address", "Address")
                        .WithMany("Issuers")
                        .HasForeignKey("IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.TaxRegime", "TaxRegime")
                        .WithMany("Issuers")
                        .HasForeignKey("IdTaxRegime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.TaxResponsibility", "TaxResponsibility")
                        .WithMany("Issuers")
                        .HasForeignKey("IdTaxResponsibility")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("TaxRegime");

                    b.Navigation("TaxResponsibility");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.ProductTax", b =>
                {
                    b.HasOne("InvoicesSystem.API.Models.Entities.Product", "Product")
                        .WithMany("ProductTaxes")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoicesSystem.API.Models.Entities.Tax", "Tax")
                        .WithMany("ProductTaxes")
                        .HasForeignKey("IdTax")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Address", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Issuers");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Country", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Customer", b =>
                {
                    b.Navigation("CustomerContacts");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Department", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("InvoicePayments");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.InvoiceDetail", b =>
                {
                    b.Navigation("InvoiceDetailTaxes");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Issuer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.PaymentMethod", b =>
                {
                    b.Navigation("InvoicePayments");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Product", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("ProductTaxes");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.Tax", b =>
                {
                    b.Navigation("InvoiceDetailTaxes");

                    b.Navigation("ProductTaxes");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.TaxRegime", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Issuers");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.TaxResponsibility", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Issuers");
                });

            modelBuilder.Entity("InvoicesSystem.API.Models.Entities.TypeIdentification", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
