version: "3.9"

networks:
  billing_network:
    driver: bridge
    name: billing_network

volumes:
  billing_db_data:


services:
  db:
    image: postgres:16
    container_name: billing_postgres
    restart: always
    environment:
      POSTGRES_DB: billing_system # Nombre de la BD
      POSTGRES_USER: postgres # Usuario
      POSTGRES_PASSWORD: postgres # Contraseña
    ports:
      - "5434:5432" # Puerto externo 5434 -> interno 5432
    volumes:
      - billing_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d billing_system" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - billing_network

  api:
    build:
      context: ..
      dockerfile: Backend/InvoicesSystem.API/Api.Dockerfile
    container_name: billing_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__PostgresDocker: "Host=billing_postgres;Port=5432;Database=billing_system;Username=postgres;Password=postgres"
    ports:
      - "8081:8080" # Host:8081 → Contenedor:8080
    networks:
      - billing_network

  frontend:
    build:
      context: ..
      dockerfile: Frontend/Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081
    container_name: billing_frontend
    restart: always
    depends_on:
      api:
        condition: service_started
    ports:
      - "3000:80"
    networks:
      - billing_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: billing_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - billing_network
